### ISSUE TITLE
Add storybook

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#60]
- [x] Also add a "recipe" on how to use the modal stack once it has been created #59 
- [x] Add recipe for the same as the above feature with #61 
- [x] Add recipe for the same as the above feature with #62
